Admin:

  # whether to re-analyze a stellar evolution and replace it in the database or not
  replace_evolutions: False

  # database options
  database_name: "/home/asimazbunzel/Projects/HMXB-NSBH/hmxb.db"
  overwrite_database: True

  # monitor always on, while waiting `waiting_time_in_sec` before re-analyzing
  keep_monitor: True
  waiting_time_in_sec: 3600

MESA:

  # template location
  template_directory: "/home/asimazbunzel/Projects/HMXB-NSBH/data/raw/templates"

  # run location
  runs_directory: "/home/asimazbunzel/Projects/HMXB-NSBH/data/raw/runs/"

  # id of the grid of simulations. Options are `mesastar` and `mesabinary`
  id: "mesabinary"

  # options needed for a summary of a MESAbinary simulation. They are used when the id flag
  # is equal to "mesabinary"
  mesabinary:

    # $MESA_DIR value
    mesa_dir: "/home/asimazbunzel/Developments/mesa-r15140"

    # whether MESAbinary evolves two stars or a star and a point-mass
    evolve_both_stars: False

    # MESAbinary and MESAstar output folders
    log_directory_binary: "LOGS_binary"
    log_directory_star1: "LOGS1"
    log_directory_star2: ""

    # filenames of MESA output
    history_name_binary: "binary_history.data"
    history_name_star1: "history.data"
    history_name_star2: ""

    # where termination code is stored
    termination_directory: "termination_codes"
    termination_name: "termination_code_star_plus_point_mass"

    # location of the core-collapse information (in case there is)
    core_collapse_directory: "cc_data"
    core_collapse_name_binary: "binary_at_core_collapse.data"
    core_collapse_name_star1: "star_at_core_collapse.data"
    core_collapse_name_star2: ""

  # as the previous options but for the case of id = "mesastar"
  mesastar:

    skip_summary: True

Stevdb:

  # filename with the list of MESA history_column names to save in database
  history_columns_list : "/home/asimazbunzel/Developments/stevdb/example/history.yaml"

  # which phases will the code track
  track_initials: True
  id_for_initials_in_database: "Initials"
  track_finals: True
  id_for_finals_in_database: "Finals"
  track_xrb_phase: False
  id_for_xrb_phase_in_database: ""
  track_ce_phase: False
  id_for_ce_phase_in_database: ""
