Admin:

  # whether to re-analyze a stellar evolution and replace it in the database or not
  replace_evolutions: False

  # database options
  database_name: "/home/asimazbunzel/Projects/HMXB-NSBH/data/mesa-xrb.db"
  overwrite_database: True

  # monitor always on, while waiting `waiting_time_in_sec` before re-analyzing
  keep_monitor: True
  waiting_time_in_sec: 3600

MESA:

  # template location
  template_directory: "/home/asimazbunzel/Projects/HMXB-NSBH/data/raw/templates"

  # run location
  runs_directory: "/home/asimazbunzel/Projects/HMXB-NSBH/data/raw/runs/"

  # id of the grid of simulations. Options are `mesastar` and `mesabinary`
  id: "mesabinary"

  mesabinary:

    # $MESA_DIR value
    mesa_dir: "/home/asimazbunzel/Developments/mesa-r15140"

    # whether MESAbinary evolves two stars or a star and a point-mass
    evolve_both_stars: False

    # MESAbinary and MESAstar output folders
    log_directory_binary: "LOGS_binary"
    log_directory_star1: "LOGS1"
    log_directory_star2: ""

    # filenames of MESA output
    history_name_binary: "binary_history.data"
    history_name_star1: "history.data"
    history_name_star2: ""

    termination_directory: "termination_codes"
    termination_name: "termination_star_plus_star"

  mesastar:

    skip_summary: True
