# This file contains values from Cookiecutter

default_context:
  project_name: "stevdb"
  project_description: "Database manager of binary stellar-evolutions"
  organization: "asimazbunzel"
  license: "GNU GPL v2.1"
  minimal_python_version: 3.7
  github_name: "asimazbunzel"
  email: "asimazbunzel@iar.unlp.edu.ar"
  version: "0.1.0"
  line_length: "100"
  create_example_template: "cli"
